#!/bin/sh

# $1 db name
# $2 username
# $3 password
# $4 dump path
#mongorestore --drop --db $1 --host mongodb1.example.net --port 3017 --username $2 --password '$3' $4
mongorestore --drop --db $1 --username $1 --password '$2' $3
